markdown: redcarpet
# Site settings
title: Pi Day - La tournée de Pi
email: staff-2016@piday.fr
description: > # this means to ignore newlines until "baseurl:"
  Site officiel de la tournée de Pi à Paris, Marseille et Lyon. Retrouvez toutes les informations utiles sur cette soirée musicale mathématique totalement transcendante !
baseurl: ""
url: "http://www.piday.fr" # the base hostname & protocol for your site
social:
  - network: github
    username: LaGauffre
  - network: twitter
    username: Lagauffrebzh
  - network: linkedin
    username: pub/pierre-olivier-goffard/a4/abb/952
  - network: facebook
    username: pierro.goffard
#<<<<<<< HEAD
#github_username:  LaGauffre
#facebook_username: Pierro.goffard
#twitter_username: LaGauffreBzh
#linkedIn_username:
#=======

gems:
  - jekyll-redirect-from

#>>>>>>> 1196153b42e10850ca6571db978716e91857429e



