markdown: redcarpet
# Site settings
title: Pi Day - La journée de Pi
email: pidaymars@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site officiel de la journée de Pi à Marseille. Retrouvez toutes les informations utiles de ce magnifique évènement!
#baseurl: "/piday.github.io"
#url: "http://www.piday.fr" # the base hostname & protocol for your site
social:
  - network: github
    username: LaGauffre
  - network: twitter
    username: Lagauffrebzh
  - network: linkedin
    username: pub/pierre-olivier-goffard/a4/abb/952
  - network: facebook
    username: pierro.goffard
#<<<<<<< HEAD
#github_username:  LaGauffre
#facebook_username: Pierro.goffard
#twitter_username: LaGauffreBzh
#linkedIn_username:
#=======



#>>>>>>> 1196153b42e10850ca6571db978716e91857429e



