markdown: redcarpet
# Site settings
title: Pi Day - Lajournée de Pi
email: pidaymars@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  All you need to know about me and my research work!
baseurl: "/piday.github.io"
#url: "http://Pierre-Olivier.goffard.me" # the base hostname & protocol for your site
social:
  - network: github
    username: LaGauffre
  - network: twitter
    username: Lagauffrebzh
  - network: linkedin
    username: pub/pierre-olivier-goffard/a4/abb/952
  - network: facebook
    username: pierro.goffard
#<<<<<<< HEAD
#github_username:  LaGauffre
#facebook_username: Pierro.goffard
#twitter_username: LaGauffreBzh
#linkedIn_username:
#=======



#>>>>>>> 1196153b42e10850ca6571db978716e91857429e



